work_dir: /home/salman/HandFormer_Assembly101/work_dirs/handformer_B21x8_test/
save_score: True

mixed: False # Enable mixed precision for faster training
feeder: feeders.feeder.Feeder

# Test or Validation
test_feeder_args:
  data_path: /home/salman/Assembly101_AR_fusion_data/data/HAND_GCN/RAW_contex30_thresh0/
  rgb_data_path: /home/salman/Assembly101_AR_fusion_data/data/HAND_VID/RAW_contex30_thresh0/
  label_path: /home/salman/Assembly101_AR_fusion_data/data/Label_contex30_thresh0/
  split_name: validation
  target_type: action # 'action' (1380 classes) or 'verb' (24 classes) or 'noun' (90 classes)
  pose_fps: 60 # Pose frames per sec. Can reduce until 15 without compromising accuracy. Frames taken across the whole clip.
  sample_cnt_pose: 120 # Number of pose frames used in the model.
  sample_cnt_vid: 8 # Number of RGB frames to sample from the video.
  p_interval: [0.85]
  sampling_strategy: crop_and_resize # 'default' or 'crop_and_resize'; 'default': uniform sampling (+zero pad or trim),'crop_and_resize': fixed fps sampling, then temporal interpolation.
  rgb_feature_source: dino # tsm / dino / resnet / tsm_ego_e4 / tsm_ego_e3 / none
  crop_scale: both # full / cropped / both
  rgb_sampling_within_window: first # first/mid/random. 
  debug: False



# # Pose-only variant with overlapping microactions
# model: models.hf_pose.HF_Pose
# model_args:
#   microaction_window_size: 15
#   num_joints: 21 # 21 or 11 or 6
#   num_classes: 1380 # For HF_PoseRGB: #actions. For HF_Pose: it can be #verbs, change target_type in feeders accordingly.

#   embedding_dim_final: 256
#   use_2d_pose: False
#   dropout: 0.2
#   microaction_overlap: 0.5
  
#   trajectory_atten_dim_per_head: 4
#   trajectory_tcn_kernel_size: 3
#   trajectory_tcn_stride: [1,2,2]
#   trajectory_tcn_dilations: [1,2]

#   use_global_wrist_reference: True
#   include_orientation_in_global_wrist_ref: True
#   use_both_wrists: True
#   separate_hands: True

#   tf_heads: 8
#   tf_layers: 2


# Pose + RGB variant with non-overlapping microactions
model: models.hf_posergb.HF_PoseRGB
model_args:
  microaction_window_size: 15
  num_joints: 21 # 21 or 11 or 6
  num_classes: 1380 # For HF_PoseRGB: #actions. For HF_Pose: it can be #verbs, change target_type in feeders accordingly.
  num_verbs: 24
  num_nouns: 90

  embedding_dim_final: 256
  use_2d_pose: False
  dropout: 0.2
  
  trajectory_atten_dim_per_head: 4
  trajectory_tcn_kernel_size: 3
  trajectory_tcn_stride: [1,2,2]
  trajectory_tcn_dilations: [1,2]

  use_global_wrist_reference: True
  include_orientation_in_global_wrist_ref: True
  use_both_wrists: True
  separate_hands: True

  tf_heads: 8
  tf_layers: 2

  rgb_input_feat_dim: 1536 # for DINO: 1536, for TSM: 2048. Must be consistent with the feature source in feeder.
  MIB_block: True
  modality: both
  rgb_frames_to_use: -1 # -1 for all frames; Implemented for 1, 2, 4 also.


# test
phase: test
device: [0]
test_batch_size: 32
weights: /home/salman/HandFormer_Assembly101/work_dirs/handformer_B21x8/weights/weights-38-52782.pt